"""add extended student profile

Revision ID: cdeb3a8812b6
Revises: 65e4d68426ef
Create Date: 2026-09-08 22:20:06.825650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeb3a8812b6'
down_revision: Union[str, Sequence[str], None] = '65e4d68426ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('location', sa.String(), nullable=True))
    op.add_column('students', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('preferred_roles', sa.String(), nullable=True))
    op.add_column('students', sa.Column('preferred_industries', sa.String(), nullable=True))
    op.add_column('students', sa.Column('preferred_work_locations', sa.String(), nullable=True))
    op.add_column('students', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('students', sa.Column('resume_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    op.drop_column('students', 'resume_url')
    op.drop_column('students', 'profile_picture_url')
    op.drop_column('students', 'preferred_work_locations')
    op.drop_column('students', 'preferred_industries')
    op.drop_column('students', 'preferred_roles')
    op.drop_column('students', 'cgpa')
    op.drop_column('students', 'semester')
    op.drop_column('students', 'location')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
